### ISSUE TITLE
Upgade to new --include-filelist and --exclude-filelist

### ISSUE THREAD

**Issue by arichiardi** [zertrin/duplicity-backup.sh#136]
Hello again, reporting duty.

When I use a warning is issued:

```
Warning: Option --include-globbing-filelist is pending deprecation and will be removed in a future release.
--include-filelist and --exclude-filelist now accept globbing characters and should be used instead.
```

I tried also to use the two option in the static ones, but then I have another warning:

```
Warning: exclude-device-files is not the first selector.
This may not be what you intended
```

**Comment by zertrin** [comment]
Thanks again for the heads-up. Since I'm running Debian jessie, I still have a quite old version of duplicity and didn't see this warning.

After looking at duplicity's CHANGELOG, I found this:

> New in v0.7.03 (2015/05/11)
> ---------------------------
> * Merged in lp:~aaron-whitehouse/duplicity/filelist_combine
>   - Merged globbing and non-globbing filelists to use the same code path
>     and all accept globbing characters. Added deprecation warning to the
>     --exclude-globbing-filelist and include-globbing-filelist options in
>     commandline.py and hid them from help output. Updated the manual
>     (and unit tests) accordingly.
>   - Note that this does trigger a change in behaviour for duplicity.
>     Previously, include patterns in include-filelist did not match files
>     in a directory that was included, so /usr/local in an include file
>     would not have matched /usr/local/doc. Now, this folder would be
>     included, as would occur if --include or the old
>     --include-globbing-filelist was used. Additional lines will therefore
>     need to be added to filelists to unambiguously exclude unwanted
>     subfolders, if this is intended.
>   - Mark --include-filelist-stdin and --exclude-fielist-stdin for
>     deprecation and hide from --help output.

while I'm still at the version 0.6.24 on jessie ^^

Well we will have to deal with that in the script indeed. However I fear that we will need to do a check on duplicity's version from the script because I can't just replace `include-globbing-filelist` and `exclude-globbing-filelist` by the versions without `-globbing` as it would break for those like me on an older version of duplicity than 0.7.03.

I'm open to suggestions on how to handle this best :)

**Comment by arichiardi** [comment]
They changed quite a lot yes, I guess that if you want to keep compatibility yes, the only solution is the one you said above.

**Comment by zertrin** [comment]
Took me more time than I care to admit, but since I upgraded duplicity to 0.7+ on my server, I finally tackled this issue.

**Comment by arichiardi** [comment]
:+1:
