### ISSUE TITLE
Appears multiple processes running on start

### ISSUE THREAD

**Issue by nilp** [zertrin/duplicity-backup.sh#148]
After execute duplicity script, when running `ps aux`, it shows multiple processes running the same time. Example:

```
root      4405  0.0  0.0 113360  1732 pts/0    S+   16:12   0:00 bash ./duplicity-backup.sh -f
root      4415  0.0  0.0 113120   660 pts/0    S+   16:12   0:00 bash ./duplicity-backup.sh -f
root      4416  0.0  0.0 113120   660 pts/0    S+   16:12   0:00 bash ./duplicity-backup.sh -f
root      4417  0.0  0.0 107896   684 pts/0    S+   16:12   0:00 tee -ia /home/user/log/duplicity/duplicity-YYYY-MM-DD_HH-MM.txt
root      4418  0.0  0.0 107896   680 pts/0    S+   16:12   0:00 tee -ia /home/user/log/duplicity/duplicity-YYYY-MM-DD_HH-MM.txt
root      4427  9.2  0.1 399332 19128 pts/0    Sl+  16:12   0:04 python2 /usr/bin/duplicity full -v3 --full-if-older-than 7D --exclude /example/lol --include=/example/lal sftp://mybackup/
```

**Comment by zertrin** [comment]
Well that's probably coming from your side. As you can see there are 3 `bash` processes running the script. That can't come from the script itself since it doesn't call itself.

Note thought that there is only one call to duplicity.

You should really use `ps faux` instead of `ps aux` to better see which process started which one (tree view).

I don't think there is anything I can do, so I'll mark as invalid and close. But feel free to reopen with more detailed information showing that something in the script is not working properly if it's the case.
