### ISSUE TITLE
Add script lauching before and after backup option 

### ISSUE THREAD

**Issue by kivengh** [zertrin/duplicity-backup.sh#150]
I could be nice If we cloud launch pre/post backup script for snapshoting LVM or more.

**Comment by zertrin** [comment]
Hi,

Thanks for submitting your idea!

I can see where it's coming from and which use-cases could benefit for that, but I'm reluctant to include this directly in the script.

My rationale consists mostly of the following points:

- This script is used by people trying to automate their backups. Since this script is not packaged, the user has to take deliberate action to launch duplicity-backup.sh (usually by adding something directly in a crontab). If some tasks are to be performed before or after calling this script, I think that it's not complicated to write a small script calling what needs to be done in the correct order, and putting that script in the crontab instead. Something like the following: `my_backups.sh`

```
#/bin/bash
do_something_before --foo --bar
/path/to/duplicity_backup.sh -c /path/to/config/file --backup
do_something_after --foo --bar
```

- Let's assume that this feature proposal would be implemented. There are so many ways that things could go wrong about launching external scripts (wrong environment variables, wrong user, difficulty to include dynamic arguments in the command to be called, quoting...). I'm not willing to have to support people reporting issues about the pre/post scripts, which in the end have nothing to do with duplicity-backup.sh itself. As per my previous point, writing a small script should be quite easy, doesn't rely on the implementation in this script to be correct and makes issues with the external scripts independent of this script.

I hope this makes sense and that you understand. Feel free to tell me if I missed something that would warrant reconsidering this decision ;-)
